using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(Camera))]
public class CharacterCamera : MonoBehaviour
{
    public Transform targetTransform;
    public Vector3 offest;
    [Range(0, 20)]public float rate = 1;

    void LateUpdate()
    {
        Vector3 targetPosition = targetTransform.position + (targetTransform.rotation * offest);

        Ray ray = new Ray(targetTransform.position, (targetPosition - targetTransform.position));
        if(Physics.Raycast(ray, out RaycastHit raycastHit))
        {
            targetPosition = raycastHit.point;
        }

        transform.position = Vector3.Lerp(transform.position, targetPosition, rate * Time.deltaTime);

        Vector3 direction = targetTransform.position - transform.position;
        transform.rotation = Quaternion.LookRotation(direction);
    }
}
